### ISSUE TITLE
Suggestion: User registration

### ISSUE THREAD

**Issue by tti0** [palkerecsenyi/grammarer#3]
The current system of deployments is rather confusing for a teacher. I propose a different system, using 'cohorts' rather than deployments.

Each school class is a 'cohort', for example, `y9-gm3` (Year 9 German, set 3), and each cohort has student members, who have a normal access code, eg `1234`. On the login page, there are two boxes, cohort and access code. The cohort box is a plaintext drop down list, of all cohorts which exist. The access code is a masked text box, maybe using https://github.com/benjamincharity/angular-keypad, as there will be no need for deployment prefixes. Users must enter both to be authenticated. This way, teachers are able to setup access to only certain vocab sections, for only certain cohorts, and permissions can be assigned on either a cohort, or student level - e.g. give the cohort `staff` admin permissions and access to all vocab lists.

On installation of Grammarer, one cohort by default exists: `staff` - these people can access the admin dashboard, create new cohorts, add students to them, and generate access codes. Then, assign a cohort a vocab list, verb table or PDF printable.

**Comment by palkerecsenyi** [comment]
Excellent idea! I shall start implementing this today

**Comment by palkerecsenyi** [comment]
See b4cf393
