### ISSUE TITLE
Suggestion: Code generation

### ISSUE THREAD

**Issue by tti0** [palkerecsenyi/grammarer#4]
The current 'add code' system requires manual input of a code. Perhaps a 'generate random' button as default, which checks against the DB?

Also, do codes have to be numeric - alphanumeric codes give us 36 ^ 4 possibilities with a 4 digit code = 1679616 - I'd make these non-case sensitive.

**Comment by palkerecsenyi** [comment]
Done in 5640bdd

**Comment by palkerecsenyi** [comment]
Codes were also made strings, as requested.
