### ISSUE TITLE
Suggestions: Admin dashboard

### ISSUE THREAD

**Issue by tti0** [palkerecsenyi/grammarer#5]
Since issue #3 - I think that the admin dashboard might need re-modelling. Perhaps two tabs: 'all users' and 'all cohorts' to perform actions to a user and to a cohort - assigning permissions, adding, deleting etc. On the 'all users' page, we can filter by cohort, card, role and deployment, and by clicking on a cohort name, we are sent to the cohorts tab, and view all in that cohort.
For PDF generation - a modal opens when you click on a button at the bottom of either tab, with tick-boxes for users / cohorts to select if to be printed, and then a print button. I think it may help if the PDF also includes generation time / date, the user who did the generation, and each little coloured box should also show the cohort name.

**Comment by palkerecsenyi** [comment]
Will use https://bulma.io/documentation/components/tabs/

**Comment by palkerecsenyi** [comment]
Mostly done in above commit, except PDF stuff.

**Comment by palkerecsenyi** [comment]
PDF now includes cohort name, will add date/time in a later release.
