### ISSUE TITLE
Bug: Never ending swirl on bad code add

### ISSUE THREAD

**Issue by tti0** [palkerecsenyi/grammarer#6]
![image](https://user-images.githubusercontent.com/14841064/40608175-956ea7b4-6262-11e8-87c9-b2cc8dee6cfd.png)

If I attempt to create a code which already exists (eg. `1571` in cohort `rabbit1` above), I get a JS `alert()`, however, the spinning white logo does not stop spinning, meaning I have to refresh the page to try again.

**Comment by palkerecsenyi** [comment]
Fixed in commit above
