### ISSUE TITLE
Bug: Limits on manual code add length

### ISSUE THREAD

**Issue by tti0** [palkerecsenyi/grammarer#7]
When adding a code manually, I have unlimited length:
![image](https://user-images.githubusercontent.com/14841064/40608338-138f35a0-6263-11e8-90f1-14305e61759a.png)
However, line 28 of https://github.com/palkerecsenyi/grammarer/blob/master/frontend/views/home.html:
`<input id="g-code" class="input is-medium" type="text" placeholder="Code..." ng-model="code" maxlength="7">`
means that a code could potentially be created, which the user cannot enter, as it would be longer that 7 chars.

**Comment by palkerecsenyi** [comment]
Fixed in commit above
