### ISSUE TITLE
Suggestion: Reset CLI script

### ISSUE THREAD

**Issue by tti0** [palkerecsenyi/grammarer#8]
Add a simple script **CLI-only** script (run like `node reset-db.js`) which resets the database to its default settings, as if fresh from the repo - get user to confirm with `Type y to continue` that all data will be deleted!

**Comment by palkerecsenyi** [comment]
Fixed in https://github.com/palkerecsenyi/grammarer/commit/64c0f5e6d955bffcdc6cad33508a714827d394d7
